  name: Docs

  on: 
    push:
      branches: [ main ]
    workflow_dispatch:
    
  jobs:      
    build-ci:
      runs-on: macos-latest
      name: Mac Build
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install .NET 6.0.300-preview.22204.3
          run: |
              curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 6.0.300-preview.22204.3 --quality preview
              dotnet --version
              
        - uses: actions/setup-node@v3
          with:
            node-version: 16
              
        - name: Restore Dependencies
          run: dotnet restore src/Makani.Docs/Makani.Docs.csproj

        - name: Publish Makani Docs
          run: dotnet publish src/Makani.Docs/Makani.Docs.csproj -c Release --output build
        
        - name: Rewrite base href
          uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
          with:
            html_path: build/wwwroot/index.html
            base_href: /makani/

        - name: Deploy to Github Pages
          uses: JamesIves/github-pages-deploy-action@v4.3.3
          with:
            token: ${{ secrets.GH_PAGES_ACCESS_TOKEN }}
            branch: makani # The branch the action should deploy to.
            folder: build/wwwroot # The folder the action should deploy.
