name: publish to nuget
on:
  workflow_dispatch:
    branches:
      - main # Default release branch, may also be named 'master' or 'develop'
    secrets:
      NUGET_API_KEY:
        required: true
jobs:
  publish:
    name: build, pack & publish
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install .NET 6.0.300-preview.22204.3
        run: |
            curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 6.0.300-preview.22204.3 --quality preview
            dotnet --version
      
      - name: Restore Dependencies
        run: dotnet restore src/Makani/Makani.csproj

      - name: Build Makani
        run: dotnet build src/Makani/Makani.csproj -c Release

      - name: Publish to NuGet
        run: dotnet nuget push --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}} --source 'https://api.nuget.org/v3/index.json' ${{github.workspace}}/packages/Makani.*.nupkg
